branches:
  only:
  - comingsoon
language: ruby
cache: bundler
sudo: false
rvm:
- 2.2.2
install:
- bundle install
- npm install
script:
- gulp deploy
after_success:
- s3_website push
- curl -X POST 'https://api.twilio.com/2010-04-01/Accounts/AC312cb948c4a3ec03d1ed446586a8c452/Messages.json'
  --data-urlencode 'To=+"$ANISHA_IPHONE"' --data-urlencode 'From=+14155240043' --data-urlencode
  'Body=SuchBrooklyn Deploy Successful!' -u AC312cb948c4a3ec03d1ed446586a8c452:"$TWILIO_TOKEN"
before_install:
- curl -X POST 'https://api.twilio.com/2010-04-01/Accounts/AC312cb948c4a3ec03d1ed446586a8c452/Messages.json'
  --data-urlencode 'To=+"$ANISHA_IPHONE"' --data-urlencode 'From=+14155240043' --data-urlencode
  'Body=SuchBrooklyn Build Started!' -u AC312cb948c4a3ec03d1ed446586a8c452:"$TWILIO_TOKEN"
before_script:
- curl -X POST 'https://api.twilio.com/2010-04-01/Accounts/AC312cb948c4a3ec03d1ed446586a8c452/Messages.json'
  --data-urlencode 'To=+"$ANISHA_IPHONE"' --data-urlencode 'From=+14155240043' --data-urlencode
  'Body=SuchBrooklyn Deploy Started!' -u AC312cb948c4a3ec03d1ed446586a8c452:"$TWILIO_TOKEN"
after_failure:
- curl -X POST 'https://api.twilio.com/2010-04-01/Accounts/AC312cb948c4a3ec03d1ed446586a8c452/Messages.json'
  --data-urlencode 'To=+"$ANISHA_IPHONE"' --data-urlencode 'From=+14155240043' --data-urlencode
  'Body=SuchBrooklyn Deploy Failure!' -u AC312cb948c4a3ec03d1ed446586a8c452:"$TWILIO_TOKEN"
env:
  global:
  - secure: UXtajsCeL4LZfPtg1ip2ZJtyFyyVvmjUypUIFQ//TirDPa7gKMTChkrOsxgsQqkQobi7W/nU4IUzmSnt/UngBsMiOEynIfBU0+aev0QXLBpvjyAoOpEea3KBTB0q3XUmtMQ6i/q1B0kg8hjFcGxvsQhewgTfPtb4H0G/LaO/288=
  - secure: KYP1AnEEutS8ZnBj337VnixTEbMnJ3BWUlnAt2EnHokXhCgBBheU95PGGHIh4auF5rzqwZeBVPKjlIF2JNkZ7Dc4WNqv16HsRQtKfv+jIwJ0EC613ia3QsP1zoAH4Xq/0IJKrS5LaImWksQODo5CJUsVR6EGr40la9sQsfJ1cpk=
  - secure: YCUphGC1JN7NYF4i69Z5gK5Y0V+d5glKUDRumDt9rmcafXsJ9+BEllzigUYXYMsVZz6Utl+LLxAxjJJbt2ubTv7oxc/pS3hL2JzAwvxLb9Zk5Ubdr+gccN+8cydKeYRSkn+aendFDpVk2tq5Q8N/ly0QMtXSwh3wxtMLeQZGgyM=
  - secure: fEPqry7X8rAQt1Re0eVUyE3IhsDy2WoMiyOZIRk2dCrU5LT0DIQNKshjpP+NTEbwE3TWMovMoA9ekqKT/TBI8cbcV7lqYom7iqB0ckk0OvOuwpxCbenS5Bvp6Cl59Oc33In92dkeg1nkGi0Iya9sYrPdhTuVYwXIkh1Z6MsMF9o=
  - secure: DYy67XCpZzF7ls+Q7vLZh3Z8aiHaQNrKHEzY77ozosGiD/cSaTQ1fSzXYB1wLr9gUInzenoL82uVtbRuJsZ3T4uFnqcK+FHW9c3lutOD4C4HoXQcVsxS/TvpHVdhYMOci1FmJykaA2pOSePTrjsyncCuObIbthRavuVBEHUFoVc=
